name: Required Code Review
on: 
  pull_request_review:
  pull_request:
    branches: ["master", "develop"]
    types: [synchronize]
    
jobs:
  check:
    name: Required Code Review
    runs-on: ubuntu-latest
    
    steps:
      - name: Required Code review
        uses: Automatic/action-required-review@v3
