name: Required Code Review
on: 
  pull_request_review:
  pull_request:
    branches: ["master", "develop"]
    types: [synchronize, opened, edited, closed, reopened, review_requested, ready_for_review]
    
jobs:
  check:
    name: Required Code Review
    runs-on: ubuntu-latest
    
    steps:
      - name: Required Code review
        uses: Automattic/action-required-review@v3
